-- Obtener descripciones de las diferentes tablas creadas mediante el script

DESCRIBE CONSULTAS;
DESCRIBE CONSULTAS_DATOS;
DESCRIBE EVENTOS;
DESCRIBE EVENTOS_RESULTADOS;
DESCRIBE LOCALIDADES;
DESCRIBE PARTIDOS;
DESCRIBE PROVINCIAS;
DESCRIBE VOTANTES;